//! Build script for `symphony-server`.
//!
//! 1. Embeds the web dashboard bundle (`web/dist`, or `$SYMPHONY_WEB_DIST`). When the bundle is
//!    missing, a small placeholder page (`src/placeholder.html`) is embedded instead and a cargo
//!    warning is printed: the Rust build never fails because the web UI was not built.
//! 2. Converts the API contract `docs/api/openapi.yaml` to JSON (served at `/api/openapi.json`).
//!    A missing or invalid contract *does* fail the build: it lives in this repository.
//!
//! Outputs (in `$OUT_DIR`): `web_assets.rs` (an `EMBEDDED_ASSETS` table plus `WEB_UI_EMBEDDED`)
//! and `openapi.json`.

use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

use sha2::{Digest, Sha256};

fn main() {
    let manifest_dir = PathBuf::from(env("CARGO_MANIFEST_DIR"));
    let out_dir = PathBuf::from(env("OUT_DIR"));
    let repo_root = manifest_dir.join("../..");

    embed_web_assets(&manifest_dir, &repo_root, &out_dir);
    convert_openapi(&repo_root, &out_dir);
}

fn env(name: &str) -> String {
    std::env::var(name).unwrap_or_else(|_| panic!("cargo did not set {name}"))
}

struct Asset {
    /// Request path without the leading `/` (always `/`-separated).
    path: String,
    /// Absolute file to `include_bytes!`.
    file: PathBuf,
    /// SHA-256 based strong ETag.
    etag: String,
}

fn embed_web_assets(manifest_dir: &Path, repo_root: &Path, out_dir: &Path) {
    println!("cargo:rerun-if-env-changed=SYMPHONY_WEB_DIST");
    let dist = std::env::var_os("SYMPHONY_WEB_DIST")
        .map(PathBuf::from)
        .unwrap_or_else(|| repo_root.join("web/dist"));
    let placeholder = manifest_dir.join("src/placeholder.html");
    println!("cargo:rerun-if-changed={}", placeholder.display());

    let mut assets = Vec::new();
    let embedded = dist.join("index.html").is_file();
    if embedded {
        // A directory path makes cargo rescan the whole bundle for modifications.
        println!("cargo:rerun-if-changed={}", dist.display());
        collect(&dist, &dist, &mut assets);
    } else {
        // Watch the parent so that running `pnpm --dir web build` later triggers a rebuild.
        let watch = dist.parent().filter(|p| p.is_dir()).unwrap_or(&dist);
        println!("cargo:rerun-if-changed={}", watch.display());
        println!(
            "cargo:warning=web/dist not found at {}; embedding a placeholder page. Run `pnpm --dir web build` and rebuild to embed the dashboard.",
            dist.display()
        );
        assets.push(asset("index.html".to_string(), placeholder));
    }
    assets.sort_by(|a, b| a.path.cmp(&b.path));

    let mut code = String::new();
    code.push_str("// @generated by crates/symphony-server/build.rs. Do not edit.\n\n");
    let _ = writeln!(
        code,
        "/// `true` when `web/dist` was embedded, `false` when the placeholder page was.\npub const WEB_UI_EMBEDDED: bool = {embedded};\n"
    );
    code.push_str(
        "/// Every embedded file, sorted by `path` (binary-searchable).\npub(crate) static EMBEDDED_ASSETS: &[EmbeddedAsset] = &[\n",
    );
    for asset in &assets {
        let _ = writeln!(
            code,
            "    EmbeddedAsset {{ path: {path:?}, content_type: {ct:?}, etag: {etag:?}, immutable: {immutable}, body: include_bytes!({file:?}) }},",
            path = asset.path,
            ct = content_type(&asset.path),
            etag = asset.etag,
            immutable = embedded && asset.path.starts_with("assets/"),
            file = asset.file.display().to_string(),
        );
    }
    code.push_str("];\n");
    write_if_changed(&out_dir.join("web_assets.rs"), code.as_bytes());
}

fn collect(root: &Path, dir: &Path, assets: &mut Vec<Asset>) {
    let mut entries: Vec<_> = fs::read_dir(dir)
        .unwrap_or_else(|err| panic!("cannot read {}: {err}", dir.display()))
        .filter_map(Result::ok)
        .collect();
    entries.sort_by_key(|entry| entry.file_name());
    for entry in entries {
        let path = entry.path();
        let name = entry.file_name().to_string_lossy().into_owned();
        if name.starts_with('.') {
            continue;
        }
        if path.is_dir() {
            collect(root, &path, assets);
        } else if path.is_file() {
            let relative = path
                .strip_prefix(root)
                .unwrap_or(&path)
                .components()
                .map(|c| c.as_os_str().to_string_lossy().into_owned())
                .collect::<Vec<_>>()
                .join("/");
            assets.push(asset(relative, path));
        }
    }
}

fn asset(path: String, file: PathBuf) -> Asset {
    let bytes =
        fs::read(&file).unwrap_or_else(|err| panic!("cannot read {}: {err}", file.display()));
    let digest = hex::encode(Sha256::digest(&bytes));
    let file = file.canonicalize().unwrap_or(file);
    Asset {
        path,
        file,
        etag: format!("\"{}\"", &digest[..20]),
    }
}

fn content_type(path: &str) -> &'static str {
    let ext = path
        .rsplit_once('.')
        .map(|(_, ext)| ext.to_ascii_lowercase());
    match ext.as_deref() {
        Some("html" | "htm") => "text/html; charset=utf-8",
        Some("js" | "mjs") => "text/javascript; charset=utf-8",
        Some("css") => "text/css; charset=utf-8",
        Some("json" | "map") => "application/json",
        Some("webmanifest") => "application/manifest+json",
        Some("txt") => "text/plain; charset=utf-8",
        Some("svg") => "image/svg+xml",
        Some("png") => "image/png",
        Some("jpg" | "jpeg") => "image/jpeg",
        Some("gif") => "image/gif",
        Some("webp") => "image/webp",
        Some("avif") => "image/avif",
        Some("ico") => "image/x-icon",
        Some("woff") => "font/woff",
        Some("woff2") => "font/woff2",
        Some("ttf") => "font/ttf",
        Some("otf") => "font/otf",
        Some("wasm") => "application/wasm",
        _ => "application/octet-stream",
    }
}

fn convert_openapi(repo_root: &Path, out_dir: &Path) {
    let source = repo_root.join("docs/api/openapi.yaml");
    println!("cargo:rerun-if-changed={}", source.display());
    let yaml = fs::read_to_string(&source)
        .unwrap_or_else(|err| panic!("cannot read the API contract {}: {err}", source.display()));
    let document: serde_json::Value = serde_yaml_ng::from_str(&yaml)
        .unwrap_or_else(|err| panic!("invalid YAML in {}: {err}", source.display()));
    let json = serde_json::to_string(&document)
        .unwrap_or_else(|err| panic!("cannot encode {} as JSON: {err}", source.display()));
    write_if_changed(&out_dir.join("openapi.json"), json.as_bytes());
}

/// Avoid touching outputs whose content did not change (keeps incremental builds quiet).
fn write_if_changed(path: &Path, contents: &[u8]) {
    if fs::read(path).ok().as_deref() == Some(contents) {
        return;
    }
    fs::write(path, contents)
        .unwrap_or_else(|err| panic!("cannot write {}: {err}", path.display()));
}
